@startuml
actor Admin
control DashboardPage
control EditItemPage
boundary Server

Admin -> DashboardPage: pilih tombol "Tambah"
DashboardPage -> EditItemPage: alih
Admin -> EditItemPage: isi data barang
Admin -> EditItemPage: pilih tombol "Simpan"
ItemPage -> Server: kirim data barang
Server -> ItemPage: kirim hasil gagal/sukses
ItemPage -> DashboardPage: alih
@enduml
