@startuml
actor Admin
boundary DashboardPage
boundary EditItemPage
control Server
entity Database

Admin -> DashboardPage: pilih tombol "Tambah"
DashboardPage -> EditItemPage: alih
Admin -> EditItemPage: isi data barang
Admin -> EditItemPage: pilih tombol "Simpan"
EditItemPage -> Server: kirim data barang
Server -> Database: tambah data
Server -> EditItemPage: kirim hasil gagal/sukses
EditItemPage -> DashboardPage: alih
@enduml
