@startuml
boundary ItemPage
boundary EditItemPage
boundary DashboardPage
control CRUDItem
control Server
entity Database

(ItemPage) --> (EditItemPage): EditItemPage(item: item)
(EditItemPage) --> (CRUDItem): CRUDItem(item: item, create: false)
(CRUDItem) -> (Server): delete()
(Server) -> (Database): DELETE FROM items WHERE ID=?
(CRUDItem) --> (DashboardPage): Navigator.pushNamedAndRemoveUntil(context, "dashboard", (route) => false)
@enduml
