@startuml
actor Admin
control ItemPage
control EditItemPage
control DashboardPage
boundary Server

Admin -> ItemPage: pilih tombol "edit"
ItemPage -> EditItemPage: alih
Admin -> EditItemPage: pilih tombol "Hapus Barang"
EditItemPage -> Server: kirim permintaan hapus barang
Server -> EditItemPage: kirim hasil sukses/gagal
EditItemPage -> DashboardPage: alih
@enduml
