@startuml
entity Item {
  + int Id
  + int Price
  + String Name
  + String Description
  + String DetailedDescription
  + String ImgUrl
  + int Weight
}

entity City {
  + String cityId
  + String provinceId
  + String type
  + String cityName
  + String postalCode

  + Map<String, dynamic> toMap()
}

entity Cost {
  + int value
  + String etd
  + String note

  + Map<String, dynamic> toMap()
}

entity Service {
  + String name
  + String description
  + List<Cost> costs;
}

entity ShippingInfo {
  + String courierName
  + City destCity;
  + Service service;
}

City --o ShippingInfo
Service --o ShippingInfo
Cost --o Service
@enduml
