@startuml
actor Admin
boundary DashboardPage
control TransactionWidget
control Permission
entity PermissionStatus
entity File

Admin -> DashboardPage: pilih tombol "Transaksi"
DashboardPage -> TransactionWidget: alih
Admin -> TransactionWidget: pilih tombol "pdf"
group kelola request penyimpanan
TransactionWidget -> Permission
Permission -> PermissionStatus
end
TransactionWidget -> File: simpan pdf

@enduml
