@startuml
actor Admin
boundary DashboardPage
boundary TransactionWidget
control AndroidAPI
entity AndroidFilesystem

Admin -> DashboardPage: pilih tombol "Transaksi"
DashboardPage -> TransactionWidget: alih
Admin -> TransactionWidget: pilih tombol "pdf"
TransactionWidget -> AndroidAPI: kelola request penyimpanan
AndroidAPI -> AndroidFilesystem: simpan pdf

@enduml
