@startuml
actor Pengguna
boundary RegistrationPage
boundary DashboardPage
control FirebaseAuth

Pengguna -> RegistrationPage: isi data registrasi
RegistrationPage -> FirebaseAuth: proses data registrasi
RegistrationPage -> DashboardPage: alih
@enduml
