@startuml
actor Pengguna
control ProfilePage
control LandingPage
boundary Firebase

Pengguna -> ProfilePage: keluar
ProfilePage -> Firebase: kirim permintaan keluar
Firebase -> ProfilePage: kirim hasil sukses/gagal
ProfilePage -> LandingPage: alih
@enduml
