@startuml
actor Pengguna
boundary LoginPage
boundary DashboardPage
control FirebaseAPI
entity FirebaseAuthentication

Pengguna -> LoginPage: isi data akun
LoginPage -> FirebaseAPI:  kirim data akun
FirebaseAPI -> FirebaseAuthentication: forward data
FirebaseAPI <- FirebaseAuthentication: kirim hasil sukses/gagal
FirebaseAPI -> LoginPage: forward hasil
LoginPage -> DashboardPage: alih
@enduml
