@startuml
actor Pengguna
boundary ProfilePage
boundary LandingPage
control FirebaseAuth

Pengguna -> ProfilePage: keluar
ProfilePage -> FirebaseAuth: kirim permintaan keluar
ProfilePage -> LandingPage: alih
@enduml
