@startuml
actor Pengguna
boundary LoginPage
boundary DashboardPage
control FirebaseAuth

Pengguna -> LoginPage: isi data akun
LoginPage -> FirebaseAuth:  proses data akun
LoginPage -> DashboardPage: alih
@enduml
