@startuml
actor Pengguna
boundary RegistrationPage
boundary DashboardPage
control FirebaseAPI
entity FirebaseAuthentication

Pengguna -> RegistrationPage: isi data registrasi
RegistrationPage -> FirebaseAPI: kirim data registrasi
FirebaseAPI -> FirebaseAuthentication: forward data
FirebaseAPI <- FirebaseAuthentication: kirim hasil sukses/gagal
FirebaseAPI -> RegistrationPage: forward hasil
RegistrationPage -> DashboardPage: alih
@enduml
