@startuml
boundary LoginPage
control FirebaseAuth
boundary DashboardPage

(LoginPage) -> (FirebaseAuth): signInWithEmailAndPassword(email, password)
(LoginPage) --> (DashboardPage): Navigator.pushnamedAndRemoveUntil(context, "dashboard", (route) => false)
@enduml
