@startuml
boundary RegistrationPage
control DashboardPage
control FirebaseAuth

(RegistrationPage) -> (FirebaseAuth): createUserWithEmailAndPassword(email, password)
(RegistrationPage) --> (DashboardPage): pushNamedAndRemoveUntil(context, "dashboard", (route) => false)

@enduml
