@startuml
boundary ProfilePage
boundary LandingPage
control FirebaseAuth.instance

(ProfilePage) -> (FirebaseAuth.instance): signOut()
(ProfilePage) --> (LandingPage): Navigator.pushNamedAndRemoveUntil(context, "landing", (route) => false)

@enduml
