@startuml
actor Pengguna
boundary ProfilePage
boundary LandingPage
control FirebaseAPI
entity FirebaseAuthentication

Pengguna -> ProfilePage: keluar
ProfilePage -> FirebaseAPI: kirim permintaan keluar
FirebaseAPI -> FirebaseAuthentication: forward data
FirebaseAPI <- FirebaseAuthentication: reply sukses/gagal
FirebaseAPI -> ProfilePage: kirim hasil sukses/gagal
ProfilePage -> LandingPage: alih
@enduml
