@startuml
actor Pengguna
boundary CartPage
boundary CheckoutPage
boundary ReceiptPage
control FirebaseAPI
entity FirebaseFirestore

Pengguna -> CartPage: checkout
CartPage -> CheckoutPage: alih
Pengguna -> CheckoutPage: isi tujuan dan kurir
Pengguna -> CheckoutPage: bayar
CheckoutPage -> FirebaseAPI: kirim data transaksi
FirebaseAPI -> FirebaseFirestore: forward data
CheckoutPage -> ReceiptPage: alih
@enduml
