@startuml
actor Pengguna
boundary CartPage
control CheckoutPage
boundary ReceiptPage
control FirebaseFirestore
control CollectionReference
entity DocumentReference

Pengguna -> CartPage: checkout
CartPage -> CheckoutPage: alih
Pengguna -> CheckoutPage: isi tujuan dan kurir
Pengguna -> CheckoutPage: bayar
group simpan data transaksi
CheckoutPage -> FirebaseFirestore
FirebaseFirestore -> CollectionReference
CollectionReference -> DocumentReference
CheckoutPage -> DocumentReference
end
CheckoutPage -> ReceiptPage: tampilkan nota transaksi
@enduml
