@startuml
boundary DashboardPage
control HistoryWidget
control FirebaseFirestore
entity CollectionReference
control Query
entity QuerySnapshot
entity DocumentReference

(DashboardPage) --> (HistoryWidget): HistoryWidget()
(HistoryWidget) --> (FirebaseFirestore): FirebaseFirestore.instance
(FirebaseFirestore) --> (CollectionReference): collection("transactions")
(CollectionReference) --> (Query): where("userId", isEqualTo: FirebaseAuth.instance.currentUser!.uid)
(Query) --> (Query): .where("date", ...dateRange).orderBy("date", descending: true)
(QuerySnapshot) <- (Query): get()
(QuerySnapshot) -u-> (DocumentReference): docs

@enduml
