@startuml
actor Pengguna
boundary DashboardPage
boundary HistoryWidget
control FirebaseAPI
entity FirebaseFirestore

Pengguna -> DashboardPage: pilih tombol riwayat
DashboardPage -> HistoryWidget: alih
HistoryWidget -> FirebaseAPI: ambil riwayat transaksi pengguna
FirebaseAPI -> FirebaseFirestore: forward request
FirebaseAPI <- FirebaseFirestore: kirim response
FirebaseAPI -> HistoryWidget: kirim riwayat transaksi pengguna
@enduml
