@startuml
actor Pengguna
boundary DashboardPage
control HistoryWidget
control FirebaseFirestore
entity CollectionReference
control Query
entity QuerySnapshot
entity DocumentReference

Pengguna -> DashboardPage: pilih tombol riwayat
DashboardPage -> HistoryWidget: alih
group ambil riwayat transaksi pengguna
HistoryWidget -> FirebaseFirestore
FirebaseFirestore -> CollectionReference
CollectionReference -> Query
Query -> QuerySnapshot
QuerySnapshot -> DocumentReference
end
@enduml
