@startuml

|pembeli|
start
:pilih tombol "Checkout" pada halaman keranjang;

|aplikasi|
:alih ke halaman checkout;

|pembeli|
:isi tujuan dan pilihan kurir;
:pilih tombol "Bayar";

|aplikasi|
:kirim data transaksi ke firebase;

|firebase|
:simpan data transaksi;

|aplikasi|
:tampilkan nota transaksi;
stop

@enduml
