@startuml
boundary CartPage
control CheckoutPage
control FirebaseFirestore
control CollectionReference
entity DocumentReference

(CartPage) --> (CheckoutPage): Navigator.push(context, MaterialPageRoute(builder: (context) => CheckoutPage(cart)))
(CheckoutPage) -> (FirebaseFirestore): FirebaseFirestore.instance
(FirebaseFirestore) --> (CollectionReference): collection("transactions")
(CollectionReference) --> (DocumentReference): doc()
(CheckoutPage) ---> (DocumentReference): set({...trxData})

@enduml
