@startuml
control HistoryWidget
boundary FirebaseFirestore
entity CollectionReference
control Query
entity QuerySnapshot
entity DocumentReference

(HistoryWidget) -> (FirebaseFirestore): FirebaseFirestore.instance
(FirebaseFirestore) -> (CollectionReference): collection("transactions")
(CollectionReference) --> (Query): where("userId", isEqualTo: FirebaseAuth.instance.currentUser!.uid)
(Query) --> (Query): .where("date", ...dateRange).orderBy("date", descending: true)
(QuerySnapshot) <- (Query): get()
(DocumentReference) <- (QuerySnapshot): docs

@enduml
