@startuml
boundary CheckoutPage
control FirebaseFirestore
entity CollectionReference
entity DocumentReference

(CheckoutPage) -> (FirebaseFirestore): FirebaseFirestore.instance
(FirebaseFirestore) -> (CollectionReference): collection("transactions")
(CollectionReference) -> (DocumentReference): doc()

@enduml
