@startuml
actor Pengguna
boundary DashboardPage
control SupportWidget
control FirebaseStorage
entity Reference

Pengguna -> DashboardPage
Pengguna -> SupportWidget: unggah bukti transaksi
SupportWidget -> FirebaseStorage: proses dan format bukti transaksi
FirebaseStorage -> Reference: simpan bukti transaksi
@enduml
