@startuml
actor Pengguna
boundary SupportWidget
control FirebaseAPI
entity FirebaseStorage

Pengguna -> SupportWidget: unggah bukti transaksi
SupportWidget -> FirebaseAPI: proses dan format bukti transaksi
FirebaseAPI -> FirebaseStorage: forward data bukti transaksi
@enduml
