@startuml
control SupportWidget
boundary FirebaseStorage
control Reference

(SupportWidget) -> (FirebaseStorage): FirebaseStorage.instance
(FirebaseStorage) --> (Reference): ref()
(Reference) --> (Reference): child("paymentConfirmations/${uid}/${timestamp}${fileExtension}")
@enduml
