@startuml
boundary DashboardPage
control SupportWidget
control FirebaseStorage
entity Reference

(DashboardPage) -> (SupportWidget): SupportWidget()
(SupportWidget) -> (FirebaseStorage): FirebaseStorage.instance
(FirebaseStorage) --> (Reference): ref()
(DashboardPage) --> (Reference): child("paymentConfirmations/${uid}/${timestamp}${fileExtension}")
@enduml
