@startuml
actor Admin
control ItemPage
control EditItemPage
control DashboardPage
boundary Server

Admin -> ItemPage: pilih tombol "edit"
ItemPage -> EditItemPage: alih
Admin -> EditItemPage: isi data baru barang
Admin -> EditItemPage: pilih tombol simpan
EditItemPage -> Server: kirim data baru barang
Server -> EditItemPage: kirim hasil sukses/gagal
EditItemPage -> DashboardPage: alih
@enduml
