@startuml
boundary ItemPage
boundary EditItemPage
control CRUDItem
entity Server

(ItemPage) -> (EditItemPage): EditItemPage(item: item)
(EditItemPage) -> (CRUDItem): CRUDItem(item: item, create: false)
(CRUDItem) -> (Server): update()
@enduml
