@startuml
actor Admin
control ItemPage
control DashboardPage
boundary Server

Admin -> ItemPage: pilih tombol "edit"
Admin -> ItemPage: isi data baru barang
Admin -> ItemPage: pilih tombol simpan
ItemPage -> Server: kirim data baru barang
Server -> ItemPage: kirim hasil sukses/gagal
ItemPage -> DashboardPage: alih
@enduml
