@startuml
left to right direction

actor Pembeli as usr
actor Admin as root

rectangle System {
(Registrasi) as signup
(Masuk) as signin

rectangle Authenticated {
(Keluar) as signout
(Lihat riwayat transaksi) as trx_history

(Tambah barang ke keranjang) as add_cart
(Hapus barang dari keranjang) as del_cart
(Lakukan transaksi) as trx
(Unggah bukti transaksi) as up_trx_receipt

(Cetak riwayat transaksi ke pdf) as pdf_trx_history
(Tambah barang ke estalase) as crt_item
(Hapus barang dari estalase) as del_item
(Perbarui barang di estalase) as upd_item
}
}

usr -- signup
usr -- signin
root -- signup
root -- signin

signup .> signin: <<extend>>
signin .> Authenticated: <<extend>>

usr -- trx_history
usr -- add_cart
usr -- del_cart
usr -- signout

add_cart .> trx: <<extend>>
add_cart .> del_cart: <<extend>>
trx .> up_trx_receipt: <<extend>>

pdf_trx_history -- root
crt_item -- root
del_item -- root
upd_item -- root

@enduml
