@startuml
left to right direction

actor Pembeli
actor Admin

(Login) as signin
(Registrasi) as signup
(Keluar) as signout
(Membuat transaksi) as trx
(Upload bukti transaksi) as up_trx_receipt
(Melihat riwayat transaksi) as trx_history
(Mencetak transaksi ke pdf) as pdf_trx
(Kelola keranjang) as mng_cart
(Kelola profil) as mng_profile
(Kelola estalase) as stock

Pembeli -- signin
Pembeli -- signup
Pembeli -- trx
Pembeli -- up_trx_receipt
Pembeli -- trx_history
Pembeli -- pdf_trx
Pembeli -- mng_cart
Pembeli -- mng_profile
Pembeli -- signout

signin -- Admin
stock -- Admin
trx_history -- Admin
pdf_trx -- Admin

signin ..> trx: <<extend>>
signin ..> up_trx_receipt: <<extend>>
signin ..> trx_history: <<extend>>
signin ..> pdf_trx: <<extend>>
signin ..> mng_cart: <<extend>>
signin ..> mng_profile: <<extend>>
signin ..> signout: <<extend>>

signin ..> stock: <<extend>>

@enduml
